## Basic config
batch_size: 2
learning_rate: 0.001
epoch: 1000

## reset image size
height: 128
width: 128

## The scale size that the net work output.
scale: 1

## Path
datas_path: '/home/sherman/projects/data/VOCdevkit/VOC2007/JPEGImages'
labels_path: '/home/sherman/projects/data/VOCdevkit/VOC2007/Annotations'