# Image dir
image_dir: '/home/sherman/projects/data/VOCdevkit/VOC2007/JPEGImages/009961.jpg'

# Select the scale
scale: 1

# The path of the target image to save
save_dir: './generated_images'

# Out put image attribute
image_width: 128
image_height: 128